export default {
  index: "Introduction",
  "why-arclens": "Why ArcLens is different",
  "how-it-works": "How it works",
  "sep-platform": { type: "separator", title: "Platform" },
  ecosystem: "Ecosystem",
  campaigns: "Campaigns",
  explorer: "Explorer",
  "builder-profiles": "Builder Profiles",
  "trust-layer": "Trust layer",
  "sep-lens": { type: "separator", title: "Lens AI" },
  "lens-ai": "Lens AI",
  economy: "The nanopayment economy",
  "agent-api": "Agent API",
  "sep-build": { type: "separator", title: "Build & future" },
  "for-builders": "For builders",
  roadmap: "Roadmap",
  resources: "Resources",
}
